### ISSUE TITLE
Misnamed Readme.rst file fails Setuptools build

### ISSUE THREAD

**Issue by Apteryks** [Snooz82/robotframework-datadriver#66]
It fails like so, due to the different capitalization used:

```
running "python setup.py" with command "build" and parameters ()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 8, in <module>
    with open("README.rst", "r", encoding="utf-8") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by Snooz82** [comment]
Fixed in 1.6.0
